[features]
seeds = false
skip-lint = false
[programs.localnet]
disperse = "6NdRdxwFxwraN3H6FszNRfPfTgyBq3tGRHPfPzM2UC9X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
